### ISSUE TITLE
I need help with this error.

### ISSUE THREAD

**Issue by rohitpeesa** [andela-foladeji/License-Plate-Recognition-Nigerian-vehicles#28]
NameError                                 Traceback (most recent call last)
<ipython-input-8-89ea8aba958f> in <module>()
     29     print("Cross Validation Result for ", str(num_of_fold), " -fold")
     30     print(accuracy_result * 100)
---> 31 current_dir = os.path.dirname(os.path.realpath(__file__))
     32 training_dataset_dir = os.path.join(current_dir, 'train')
     33 image_data, target_data = read_training_data(training_dataset_dir)

NameError: name '__file__' is not defined

**Comment by andela-foladeji** [comment]
@rohitpeesa what did you run to get this error? However, the error is quite self explanatory, you can try printing `file` just before that line to ensure that it's defined.

**Comment by rohitpeesa** [comment]
ok thanks
