### ISSUE TITLE
Empty GUI

### ISSUE THREAD

**Issue by shivwick123** [andela-foladeji/License-Plate-Recognition-Nigerian-vehicles#30]
When I execute the project via cmd, the GUI shows up but nothing is responding i.e. its not reading the test image. I just can't interact with the GUI in any way.
![gui](https://user-images.githubusercontent.com/37579480/43989606-e62c06cc-9d6a-11e8-8999-127f24e11619.png)

**Comment by andela-foladeji** [comment]
@shivwick123 check your computer's status bar at the very top of the screen. The menu should be there
